baseURL = "https://sleepy-noether-c999b7.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"

themesDir = "./../."
theme = "docs-revamp-theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"

[params]
  themeVariant = "grey"

[module]

[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "content"
  target = "content"

[[module.mounts]]
  source = "generatedcontent"
  target = "content"

[[module.mounts]]
  source = "static"
  target = "static"