baseURL = "https://sleepy-noether-c999b7.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "drt"


[build]
writeStats = true

[module]

[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "content"
  target = "content"

[[module.mounts]]
  source = "generatedcontent"
  target = "content"

[[module.mounts]]
  source = "static"
  target = "static"

[[module.mounts]]
  source = "data"
  target = "data"