baseURL = "https://sleepy-noether-c999b7.netlify.app/v2/"
languageCode = "en-us"
title = "My New Hugo Site"

publishDir = "public/v2"

theme = "github.com/pointyfar/drt"

[build]
writeStats = true

[module]

[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "content"
  target = "content"

[[module.mounts]]
  source = "generatedcontent"
  target = "content"

[[module.mounts]]
  source = "static2"
  target = "static"

[[module.mounts]]
  source = "data"
  target = "data"

